accounts/urls.py
from django.urls import path
from .views import (
   RegistUserView,HomeView,UserLoginView,UserLogoutView,
   ProfileEditView, UserListView
)
from . import views

app_name = 'accounts'
urlpatterns = [
   path('home/', HomeView.as_view(), name='home'),
   path('regist/', RegistUserView.as_view(), name='regist'),
   path('login/', UserLoginView.as_view(), name='login'),
   path('logout/', UserLogoutView.as_view(), name='logout'),
   path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'),
   path('userlist/', UserListView.as_view(), name='userlist'),
   path('mk_relation/<int:pk>/', views.mk_relation, name='mk_relation'),
   path('rm_relation/<int:pk>/', views.rm_relation, name='rm_relation'),
]

myposts/urls.py
from os import name
from django.conf.urls import url
from django.urls import path
from . import views
from .views import (
   PostCreateView, PostListView, PostUpdateView,
   PostDeleteView, MyPostsView,
   FollowingView, FollowersView, GalleryView, 
   ProfileCreateView, ProfileEditView, ProfileDeleteView, UserProfileView
)
app_name = 'myposts'
urlpatterns = [
   path('create/', PostCreateView.as_view(), name='create'),
   path('postlist/', PostListView.as_view(), name='postlist'),
   path('update/<int:pk>', PostUpdateView.as_view(), name='update'),
   path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
   path('myposts/', MyPostsView.as_view(), name='myposts'),
   path('add_favourite/<int:pk>/', views.add_favourite, name='add_favourite'),
   path('rm_favourite/<int:pk>/', views.remove_favourite, name='rm_favourite'), 
   path('follower/', FollowersView.as_view(), name='follower'), 
   path('following/', FollowingView.as_view(), name='following'),
   path('gallery/', GalleryView.as_view(), name='gallery'), 
   path('add_file/', views.add_file, name='add_file'),
   path('createprofile/', ProfileCreateView.as_view(), name='createprofile'),
   path('editprofile/<int:pk>', ProfileEditView.as_view() ,name='editprofile'),
   path('deleteprofile/<int:pk>',ProfileDeleteView.as_view(),name='deleteprofile'),
   path('userprofile/',UserProfileView.as_view(),name='userprofile'),
]

sns/urls.py
from django.contrib import admin
from django.forms.widgets import Media
from django.urls import path, include
from django.conf.urls.static import static
from . import settings  # mediaを使うために

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
   path('admin/', admin.site.urls), 
   path('accounts/', include('accounts.urls')),
   path('myposts/', include('myposts.urls')), 
]
# mediaを使うために追加
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

myposts/models.py
from django.core.validators import ProhibitNullCharactersValidator
from django.db import models
from django.db.models.deletion import CASCADE

class Post(models.Model):
	owner = models.ForeignKey('accounts.User', verbose_name='オーナー', on_delete=models.CASCADE, related_name='photo_owner')
	photo = models.ImageField(upload_to='images/',verbose_name='photo')
	comment = models.TextField(max_length=300, blank=True)
	pub_date = models.DateTimeField(auto_now_add=True)
	meow_count = models.IntegerField(default=0)
	detail = models.BooleanField(default=False,verbose_name="里親募集")
	gender = models.BooleanField(default=True, blank=True)
	age = models.CharField(max_length=30, blank=True)
	kind = models.CharField(max_length=30, blank=True)
	class Meta:
		db_table = 'posts'
		ordering = ('-pub_date',)

class Gallery(models.Model):
   # Imageのオーナーを設定する
   owner = models.ForeignKey('accounts.User', verbose_name='オーナー', on_delete=models.CASCADE)
   pub_date = models.DateTimeField(auto_now_add=True)
   photo = models.ImageField(upload_to='gallery/')
   
   class Meta:
       db_table = 'gallery'
   def __str__(self):
       return str(self.pk)

class Profile(models.Model):
	owner = models.ForeignKey('accounts.User', related_name='pfofile_owner', on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='avatar/', verbose_name="アイコン画像",blank=True, null=True)  
	prof = models.CharField(max_length=300, blank=True, null=True, verbose_name='自己紹介')
	sato_oya = models.BooleanField(blank=False)


	class Meta:
		db_table = 'profiles'
	def __str__(self):
		return str(self.pk)

myposts/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import Post, Profile

class PostCreateForm(forms.ModelForm):
   class Meta:
        model = Post
        fields = (
            'comment',
            'photo',
            'detail',
        )
        widgets = {
           'comment': forms.Textarea(
               attrs={'rows': 10, 'cols': 30,
                      'placeholder': 'ここに入力してください'}
            ),
        }
    

class PostUpdateForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = (
           'comment',
           'photo',
           'detail'
       )
       widgets = {
           'comment': forms.Textarea(
               attrs={'rows': 10, 'cols': 30}
           ),
       }
#追加
class FindForm(forms.Form):
    find = forms.CharField(label='Find', required=False, widget=forms.TextInput(attrs={'class':'form-control'}))


class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'avatar',
            'prof',
            'sato_oya',
        )
        widgets = {
            'prof':forms.Textarea(
                attrs={'rows': 10, 'cols': 30,
                'placeholder': 'ここに入力してください'}

            )
        }

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'avatar',
            'prof',
            'sato_oya',
        )
        widgets = {
            'prof':forms.Textarea(
                attrs={'rows': 10, 'cols': 30,}
            ),
        }

myposts/views.py
from re import template
import re
from django.db.models.fields.files import ImageField
from django.http import request, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Gallery, Profile
from .forms import PostCreateForm, PostUpdateForm, ProfileCreateForm, ProfileEditForm #追加
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q, query
from accounts.models import Relationship,User
from myposts import models

from functools import reduce
from operator import and_

class PostCreateView(LoginRequiredMixin, CreateView):
	template_name = 'myposts/create.html'
	form_class = PostCreateForm
	success_url = reverse_lazy('myposts:create')

	def form_valid(self, form):
		# formに問題なければ、owner id に自分のUser idを割り当てる     
		# request.userが一つのセットでAuthenticationMiddlewareでセットされている。
		form.instance.owner_id = self.request.user.id
		messages.success(self.request, 'Done')
		return super(PostCreateView, self).form_valid(form)
		
	def form_invalid(self, form):
		messages.warning(self.request, 'Failed')
		return redirect('myposts:create')
	
	def newPost(request):
		if request.method == "POST":
			form = PostCreateForm(request.POST)
			if form.is_valid():
				post = Post()
				print(request)
				post.photo = request.FILES['photo']
				post.save()
				return redirect('myposts:myposts')
		else:
			form = PostCreateForm()
		return render(request, 'myposts/create.html',{'form':form})


class PostListView(LoginRequiredMixin, ListView):
	template_name = 'myposts/postlist.html'
	model = Post
	paginate_by = 5

# Postsテーブルの全データを取得するメソッド定義
# テンプレートでは、object_listとしてreturnの値が渡される
	def get_queryset(self):
		word = self.request.GET.get('keyword')

		if word:
			object_list = Post.objects.filter(
				Q(comment__icontains=word)
			)
		else:
			object_list = Post.objects.all()
		return object_list

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = self.request.user
		context['favourite_list'] = user.favourite_post.all()

		return context

def add_favourite(request, pk):
   # postのpkをhtmlから取得
   post = get_object_or_404(Post, pk=pk)
   # ログインユーザーを取得
   user = request.user
   # ログインユーザーをfavoritePostのUser_idとして、post_idは
   # 上で取得したPostを記録
   user.favourite_post.add(post)
   return redirect('myposts:postlist')

def remove_favourite(request, pk):
   # postのpkをhtmlから取得
   post = get_object_or_404(Post, pk=pk)
   # ログインユーザーを取得
   user = request.user
   # ログインユーザーをfavoritePostのUser_idとして、post_idは
   # 上で取得したPostを記録
   user.favourite_post.remove(post)
   return redirect('myposts:postlist')

class PostUpdateView(LoginRequiredMixin, UpdateView): 
	model = Post
	form_class = PostUpdateForm
	template_name = 'myposts/update.html'
	def form_valid(self, form):
		messages.success(self.request, '更新が完了しました')
		return super(PostUpdateView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('myposts:update', kwargs={'pk': self.object.id})  
		
	def form_invalid(self, form):
		messages.warning(self.request, '更新が失敗しました')
		return reverse_lazy('myposts:update', kwargs={'pk': self.object.id})

class PostDeleteView(LoginRequiredMixin, DeleteView):
	model = Post
	template_name = 'myposts/delete.html'

# deleteviewでは、SuccessMessageMixinが使われないので設定する必要あり
	success_url = reverse_lazy('myposts:myposts')
	success_message = "投稿は削除されました。"
# 削除された際にメッセージが表示されるようにする。
	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(PostDeleteView, self).delete(request, *args, **kwargs)

class MyPostsView(LoginRequiredMixin, ListView):
# テンプレートを指定
	template_name = 'myposts/myposts.html'
# 利用するモデルを指定
	model = Post
# ページネーションの表示件数
	paginate_by = 6

# Postsテーブルのowner_idが自分自身の全データを取得するメソッド定義
	def get_queryset(self):
		qs = Post.objects.filter(owner_id=self.request.user)
		return qs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = self.request.user

		qs = Post.objects.filter(owner_id=self.request.user)
		# qsのレコード数をmy_posts_countというコンテキストとして設定
		context['my_posts_count'] = qs.count()
		# Postsテーブルの全データを取得しpost_listへ格納
		context['favourite_list'] = user.favourite_post.all()
		context['following_list'] = Relationship.objects.filter(follower_id=user.id)
		# 自分がfollowしているidのみをmy_follow_listとして取得
		context['my_follow_list'] = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id', flat=True)
		# 自分がフォローしている人をfollowingsとして取得
		followings = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id')
		context['following_count'] = User.objects.filter(id__in=followings).count()
		# 自分をフォローしている人をfollowersとして取得
		followers = (Relationship.objects.filter(following_id=user.id)).values_list('follower_id')
		# context['followers_data] = User.objects.filter(id__in=followers).count()
		context['follower_count'] = followers.count()
		return context

class FollowersView(LoginRequiredMixin, ListView):
   # テンプレートを指定
   template_name = 'myposts/followers.html'
   # 利用するモデルを指定
   model = Relationship

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       user = self.request.user
       # Postsテーブルの自分の投稿数をmy_posts_countへ格納
       context['my_posts_count'] = Post.objects.filter(owner_id=self.request.user).count()
       # 自分がフォローしている人をfollowingsとして取得
       followings = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id')
       # 自分がフォローしている人のオブジェクトを取得
       context['following_list'] = User.objects.filter(id__in=followings)
       # 自分がフォローしている人の数を取得
       context['following_count'] = User.objects.filter(id__in=followings).count()
       # 自分をフォローしている人をfollowersとして取得
       followers = (Relationship.objects.filter(following_id=user.id)).values_list('follower_id')
       # 自分をフォローしている人の数を取得
       context['follower_list'] = User.objects.filter(id__in=followers)
       return context

class FollowingView(LoginRequiredMixin, ListView):
   # テンプレートを指定
   template_name = 'myposts/followings.html'
   # 利用するモデルを指定
   model = Relationship

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       user = self.request.user
       # Postsテーブルの自分の投稿数をmy_posts_countへ格納
       context['my_posts_count'] = Post.objects.filter(owner_id=self.request.user).count()
       # 自分がフォローしている人をfollowingsとして取得
       followings = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id')
       # 自分がフォローしている人のオブジェクトを取得
       context['following_list'] = User.objects.filter(id__in=followings)
       # 自分をフォローしている人をfollowersとして取得
       followers = (Relationship.objects.filter(following_id=user.id)).values_list('follower_id')
       # 自分をフォローしている人の数を取得
       context['follower_count'] = User.objects.filter(id__in=followers).count()
       return context

# file(=画像)をアップロードする関数
def add_file(request):
   if request.method == "POST":        
       # ログインユーザーを取得
       user = request.user
       # 画像をテンプレートからfileとして取得
       pict = request.FILES.get('file')
       # Galleryモデルにオーナーと画像を保存
       Gallery.objects.create(owner = user, image=pict)
       return HttpResponse('')
   return HttpResponse('post error')
   
class GalleryView(LoginRequiredMixin,ListView):
   template_name = 'myposts/gallery.html'
   # 利用するモデルを指定
   model = Gallery    
   
   # Galleryテーブルのowner_idが自分自身の全データを取得するqs
   def get_queryset(self):  
       qs = Gallery.objects.filter(owner_id=self.request.user)
       return qs

class ProfileCreateView(LoginRequiredMixin, CreateView):
	template_name = 'myposts/createprofile.html'
	form_class = ProfileCreateForm
	success_url = reverse_lazy('myposts:createprofile')

	def form_valid(self, form):
		# formに問題なければ、owner id に自分のUser idを割り当てる     
		# request.userが一つのセットでAuthenticationMiddlewareでセットされている。
		form.instance.owner_id = self.request.user.id
		messages.success(self.request, 'Done')
		return super(ProfileCreateView, self).form_valid(form)
		
	def form_invalid(self, form):
		messages.warning(self.request, 'Failed')
		return redirect('myposts:createprofile')

	def profilePost(request):
		if request.method == "POST":
			form = ProfileCreateForm(request.POST)
			if form.is_valid():
				post = Profile()
				print(request)
				post.avatar = request.FILES['アイコン画像']
				post.save()
				return redirect('myposts:myposts')
		else:
			form = ProfileCreateForm()
		return render(request, 'myposts/createprofile.html',{'form':form})


class ProfileEditView(LoginRequiredMixin, UpdateView):
	model = Profile
	form_class = ProfileEditForm
	template_name = 'myposts/editprofile.html'

	def form_valid(self, form):
		messages.success(self.request, '更新が完了しました')
		return super(ProfileEditView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('myposts:editprofile', kwargs={'pk': self.object.id})  
		
	def form_invalid(self, form):
		messages.warning(self.request, '更新が失敗しました')
		return reverse_lazy('myposts:editprofile', kwargs={'pk': self.object.id})

class ProfileDeleteView(LoginRequiredMixin, DeleteView):
	model = Profile
	template_name = 'myposts/deleteprofile.html'

# deleteviewでは、SuccessMessageMixinが使われないので設定する必要あり
	success_url = reverse_lazy('myposts:myposts')
	success_message = "投稿は削除されました。"
# 削除された際にメッセージが表示されるようにする。
	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(ProfileDeleteView, self).delete(request, *args, **kwargs)

class UserProfileView(LoginRequiredMixin,ListView):
	model = Profile
	template_name= 'myposts/userprofile.html'

	def get_queryset(self):
		return Profile.objects.all()

templates/myposts/delete.html
{% extends 'base.html' %}
{% block content %}
{#    投稿したユーザーしか削除できない制約を追加#}
   {% if object.owner_id == user.id %}
       <form method="POST">
       {% csrf_token %}
       <p>「{{ object.comment }}」を削除しますか？</p>
       <button type="submit" class="btn btn-default btn-danger">
           削除する
       </button>
   </form>
       {% else %}
       <h1>{{ user.get_username }}さんの投稿ではありません。</h1>
   {% endif %}
{% endblock %}

templates/myposts/followers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <div class="content-wrapper">
       <div class="container-fluid">
           <div class="row">
               <!--ページタイトル-->
               <aside class="col-sm-4">
                   <div class="card">
                       <div class="card-header">
                           <h3 class="card-title text-center">{{ user.get_username }}</h3>
                       </div>
                       <div class="card-body">
                           {# ユーザーがプロフィール画像を持っている場合#}
                           {% if user.avatar %}
                               <img class="rounded img-fluid mx-auto d-block"
                                   src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                               {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                           {% else %}
                               <img class="rounded img-fluid mx-auto d-block"
                                   src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                           {% endif %}
                       </div>
                       <a class="btn btn-outline-secondary btn-sm"
                           href="{% url 'accounts:edit_profile' %}" role="button">Edit Profile</a>
                   </div>
               </aside>
               <div class="col-sm-8">
                   <ul class="nav nav-tabs nav-justified mb-3">
                       <li class="nav-item"><a href="{% url 'myposts:myposts' %}" class="nav-link active">MyPosts List
                           {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                           <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        {# ここから、リンク設定とBadgeの設定を変更 #}
                       <li class="nav-item"><a href="{% url 'myposts:following' %}" class="nav-link">Followings
                           {#  following数を表示#}
                           <span class="badge badge-secondary">{{ following_count }}</span></a></li>
                       <li class="nav-item"><a href="{% url 'myposts:follower' %}" class="nav-link">Followers
                           {#  follower数を表示#}
                           <span class="badge badge-secondary">{{ follower_list | length }}</span></a></li>
						   {# ここまで、リンク設定とBadgeの設定を変更 #}
                   </ul>
                   <!-- テーブル表の定義 -->
                   <div class="table table-responsive">
                       <table id='follower_list'
                              class="table table-striped table-bordered table-hover">
                           <!-- 表の列の定義-->
                           <thead>
                           <tr>
								{# 列名と幅を変更 #}
                               <th class="text-center" style="width: 50%">User</th>
                               <th class="text-center" style="width: 50%">Follow/Unfollow</th>
                           </tr>
                           </thead>
                           <!-- ここまでが表の列の定義-->
                           <!-- 表のデータ部分の表示-->
                           <tbody>
							{# follower_list:自分をお気に入り登録してくれているユーザーのリスト #}
                           {% for item in follower_list %}
                               <tr class="text">
                                   <td class="text-center">
                                    {% if item.avatar %}
                                   <img src="{{ item.avatar.url }}"
                                    id="avatar-thumbnail" alt="avatar_thumbnail">
                                    {# ユーザーがプロフィール画像を持ってない場合は”avatar_thumbnailを表示 #}
                                    {% else %}
                                   <img class="rounded img-fluid mx-auto d-block" alt="avatar_thumbnail">
                                    {% endif %}
									{{ item.username }}
                                   </td>
                                   <td class="text-center align-middle">
									{# 対象ユーザーを自分もお気に入り登録している場合 #}                                        
										{% if item in following_list %}
											{# Unfollowボタンで対象ユーザーに対して、rm_relation関数を呼び出してお気に入り解除 #}  
											<form action="{% url 'accounts:rm_relation' pk=item.id %}" method="post">
												<button type="submit" class="btn btn-outline-danger btn-sm" name="button">
													Unfollow
												</button>
												{% csrf_token %}
											</form>
										{# 対象ユーザーを自分がお気に入り登録していない場合 #}     
										{% else %}
											<form action="{% url 'accounts:mk_relation' pk=item.id %}" method="post">
												<button type="submit" class="btn btn-outline-primary btn-sm" name="button">
													Follow
												</button>
												{% csrf_token %}
											</form>
										{% endif %}
							        </td>
                               </tr>
                           {% endfor %}
                           </tbody>
                           <!-- ここまでが表のデータ部分の表示-->
                       </table>
                       <!-- ここまでがテーブル表の定義 -->
                   </div>
               </div>
           </div>
       </div>
   </div>
{% endblock %}

templates/myposts/followings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <div class="content-wrapper">
       <div class="container-fluid">
           <div class="row">
               <!--ページタイトル-->
               <aside class="col-sm-4">
                   <div class="card">
                       <div class="card-header">
                           <h3 class="card-title text-center">{{ user.get_username }}</h3>
                       </div>
                       <div class="card-body">
                           {# ユーザーがプロフィール画像を持っている場合#}
                           {% if user.avatar %}
                               <img class="rounded img-fluid mx-auto d-block"
                                   src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                               {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                           {% else %}
                               <img class="rounded img-fluid mx-auto d-block"
                                   src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                           {% endif %}
                       </div>
                       <a class="btn btn-outline-secondary btn-sm"
                           href="{% url 'accounts:edit_profile' %}" role="button">Edit Profile</a>
                   </div>
               </aside>
               <div class="col-sm-8">
                   <ul class="nav nav-tabs nav-justified mb-3">
                       <li class="nav-item"><a href="{% url 'myposts:myposts' %}" class="nav-link active">MyPosts List
                           {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                           <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        {# ここから、リンク設定とBadgeの設定を変更 #}
                       <li class="nav-item"><a href="{% url 'myposts:following' %}" class="nav-link">Followings
                           {#  following数を表示#}
                           <span class="badge badge-secondary">{{ following_count }}</span></a></li>
                       <li class="nav-item"><a href="{% url 'myposts:follower' %}" class="nav-link">Followers
                           {#  follower数を表示#}
                           <span class="badge badge-secondary">{{ follower_list | length }}</span></a></li>
						   {# ここまで、リンク設定とBadgeの設定を変更 #}
                   </ul>
                   <!-- テーブル表の定義 -->
                   <div class="table table-responsive">
                       <table id='follower_list'
                              class="table table-striped table-bordered table-hover">
                           <!-- 表の列の定義-->
                           <thead>
                           <tr>
								{# 列名と幅を変更 #}
                               <th class="text-center" style="width: 50%">User</th>
                               <th class="text-center" style="width: 50%">Follow/Unfollow</th>
                           </tr>
                           </thead>
                           <!-- ここまでが表の列の定義-->
                           <!-- 表のデータ部分の表示-->
                           <tbody>
							{# follower_list:自分をお気に入り登録してくれているユーザーのリスト #}
                           {% for item in following_list %}
                               <tr class="text">
                                   <td class="text-center">
                                    {% if item.avatar %}
                                        <img src="{{ item.avatar.url }}"
                                        id="avatar-thumbnail" alt="avatar_thumbnail">
                                    {# ユーザーがプロフィール画像を持ってない場合は”avatar_thumbnailを表示 #}
                                    {% else %}
                                        <img class="rounded img-fluid mx-auto d-block" alt="avatar_thumbnail">
                                    {% endif %}
									{{ item.username }}
                                   </td>
                                   <td class="text-center align-middle">
									{# Unfollowボタンで対象ユーザーに対して、rm_relation関数を呼び出してお気に入り解除 #}                                        
									<form action="{% url 'accounts:rm_relation' pk=item.id %}" method="post">
											<button type="submit" class="btn btn-outline-danger btn-sm" name="button">
												Unfollow
											</button>
											{% csrf_token %}
									</form>
							        </td>
                               </tr>
                           {% endfor %}
                           </tbody>
                           <!-- ここまでが表のデータ部分の表示-->
                       </table>
                       <!-- ここまでがテーブル表の定義 -->
                   </div>
               </div>
           </div>
       </div>
   </div>
{% endblock %}

templates/myposts/postlist.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container flud">
        <div class="row">
            <div class="col-sm-8">
                <!-- テーブル表の定義 -->
                {# デフォルトはobject_listとなるが、view.pyでcontextとして指定#}
                {% for item in object_list %}
                <div class="table table-responsive">
                    <table id='post_list' class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr><th><h5 style="text-align: right; float: right; font-size: medium;">{{ item.pub_date}}</h5><h5 style="text-align: left;">{{ item.owner }}</h5></th></tr>
                        </thead>
                        <tbody>
                            <tr><th>
                                <div class="card-body" id="photo"><img class="rounded img-fluid mx-auto d-block" src="{{ item.photo.url }}" 
                                    style="display:flex;align-items: center;width: auto;justify-content: center;"></th>
                            </tr>
                            <tr>
                                <th>
                                    {% if item in favourite_list %}
                                    <div style="text-align: left;"><form action="{% url 'myposts:rm_favourite' pk=item.pk %}" method="post">
                                        <button type="submit" class="btn btn-link" name="button">
                                        <i class="fas fa-paw"></i>
                                        </button>
                                        {% csrf_token %}
                                        </form>
                                    {% else %}
                                        {#  object_listの要素をitemとして取り出しているので、item.pkでpk取得#}
                                        <form action="{% url 'myposts:add_favourite' pk=item.pk %}" method="post">
                                        <button type="submit" class="btn btn-link" name="button">
                                        <i class="fa fa-paw" style="color: gray;"></i>
                                        </button>
                                        {% csrf_token %}
                                    </form></div>
                                    {% endif %}
                                </th>
                            </tr>
                            <tr><th><h6>{{ item.comment }}</h6></th></tr>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {#   django-bootstrap4のページネーション#}
                {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
            </div>
            <aside class="col-sm-4">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title text-center">search posts</div>
                    </div>
                <form class="form-inline my-2" method="GET" action="{% url 'myposts:postlist' %}">
                   <input type="text" class="form-control" name="keyword" value="{{ request.GET.kewword }}">
                   <button type="submit" value="search" class="btn btn-primary">検索</button>
                </form>
                </div>
           </aside>

        </div>
    </div>
</div>
{% endblock %}